---
# SPDX-FileCopyrightText: Â© 2018 Martin Michlmayr <tbm@cyrius.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

build: false
cache:
  - C:\strawberry
environment:
  PYTHON: 'C:\Python36'

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --notest --installdeps .
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install -U git+https://github.com/beancount/beancount/

build_script:
  - cd tests
  - runtests.bat
